name: jentrification
favicon: null
layout_spectrum: 0.09168940642848611
typography_spectrum: 0.23953453614376485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323743'
    - '#ffffff'
    - '#cd0000'
    - '#a5a7ac'
    - '#f85a50'
  brandStrength: 0.3125
  lightness: 0.8421408971771598
  saturation: 0.28908465965650976
  rhythmicContrast: 0.5526997712440789
purpose: []
